### PR TITLE
Modified the CRL import to perform the import in parallel

### PR DESCRIPTION
**Pull request by stustison**
For sufficiently large CRL files, the import can take several hours. This will make it only take as long as the largest CRL.

### CODE REVIEW

**Comment by xipki** [comment]
Do you have performance data:

**Comment by stustison** [comment]
I missed your comment here, I can get some metrics first.

**Comment by stustison** [comment]
I'm going to go ahead and close this PR. It improves the performance, but only marginally. I don't feel like the improvement is worth the cost to complexity.

**Comment by xipki** [comment]
Thanks for the contribution and experience.

**Pull request closed without merging**
